---
name: CI
on: [pull_request]
defaults:
  run:
    working-directory: 'kazauwa.headscale'

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: 'kazauwa.headscale'

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24
        with:
          working_directory: 'kazauwa.headscale'
