---
# keepalived Role Metadata

galaxy_info:
  author: Home Lab Infrastructure Team
  description: Deploy keepalived for Virtual IP high availability
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - keepalived
    - high-availability
    - vrrp
    - networking
    - loadbalancer

dependencies: []
  # Add role dependencies here if needed
