---
# Pre-commit hooks for Home Lab Infrastructure
# https://pre-commit.com/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']  # Allow custom YAML tags
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending

  # Ansible-lint disabled due to module compatibility issues with Python 3.13
  # - repo: https://github.com/ansible/ansible-lint
  #   rev: v24.12.2
  #   hooks:
  #     - id: ansible-lint
  #       files: \.(yaml|yml)$
  #       exclude: ^(\.github|docs)/

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ['-d', 'relaxed']
