---
# Tailscale Installation Tasks
# Installs and configures Tailscale VPN with SSH enabled

- name: Check if Tailscale is already installed
  ansible.builtin.stat:
    path: /usr/bin/tailscale
  register: tailscale_binary
  tags: [tailscale]

- name: Install Tailscale
  when: not tailscale_binary.stat.exists
  tags: [tailscale]
  block:
    - name: Download Tailscale installation script
      ansible.builtin.get_url:
        url: https://tailscale.com/install.sh
        dest: /tmp/tailscale_install.sh
        mode: '0755'

    - name: Run Tailscale installation script
      ansible.builtin.command: /tmp/tailscale_install.sh
      changed_when: true

    - name: Remove Tailscale installation script
      ansible.builtin.file:
        path: /tmp/tailscale_install.sh
        state: absent

- name: Check Tailscale status
  ansible.builtin.command: tailscale status --json
  register: tailscale_status
  changed_when: false
  failed_when: false
  tags: [tailscale]

- name: Authenticate Tailscale with ephemeral key
  ansible.builtin.command: >
    tailscale up
    --authkey={{ tailscale_auth_key }}
    --ssh
    --accept-routes
  when: tailscale_status.rc != 0 or 'Logged out' in tailscale_status.stdout
  changed_when: true
  no_log: true
  tags: [tailscale]

- name: Ensure Tailscale service is enabled and running
  ansible.builtin.systemd:
    name: tailscaled
    enabled: true
    state: started
  tags: [tailscale]

- name: Get Tailscale IP address
  ansible.builtin.command: tailscale ip -4
  register: tailscale_ip
  changed_when: false
  failed_when: false
  tags: [tailscale]

- name: Display Tailscale configuration
  ansible.builtin.debug:
    msg: |
      Tailscale configured successfully
      Tailscale IP: {{ tailscale_ip.stdout if tailscale_ip.rc == 0 else 'Not connected' }}
      SSH enabled via Tailscale
  tags: [tailscale]
