---
# Tor Exit Node Service Handlers

- name: Restart tor
  ansible.builtin.systemd:
    name: tor
    state: restarted
    daemon_reload: true
  become: true

- name: Reload tor
  ansible.builtin.systemd:
    name: tor
    state: reloaded
  become: true

- name: Restart unbound
  ansible.builtin.systemd:
    name: unbound
    state: restarted
  become: true

- name: Reload unbound
  ansible.builtin.systemd:
    name: unbound
    state: reloaded
  become: true

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
  become: true

- name: Reload fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: reloaded
  become: true

- name: Restart sshd
  ansible.builtin.systemd:
    name: ssh
    state: restarted
  become: true

- name: Reload sshd
  ansible.builtin.systemd:
    name: ssh
    state: reloaded
  become: true

- name: Reload ufw
  ansible.builtin.ufw:
    state: reloaded
  become: true
  when: tor_firewall_type == 'ufw'

- name: Reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
  become: true
  when: tor_firewall_type == 'firewalld'

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart prometheus-tor-exporter
  ansible.builtin.systemd:
    name: prometheus-tor-exporter
    state: restarted
  become: true
  when: tor_enable_prometheus_exporter | bool

- name: Update grub
  ansible.builtin.command: update-grub
  become: true
  changed_when: false
  when: ansible_os_family == "Debian"

- name: Sysctl reload
  ansible.builtin.systemd:
    name: systemd-sysctl
    state: restarted
  become: true
