---
# Pi-hole Configuration Variables
# Override default values from role defaults here

# ============================================
# Namespace Configuration
# ============================================
pihole_namespace: "pihole"

# ============================================
# Container Image
# ============================================
pihole_image: "pihole/pihole"
pihole_image_tag: "2024.07.0"  # Pin to specific version for production
pihole_image_pull_policy: "IfNotPresent"

# ============================================
# DNS Configuration
# ============================================
# Timezone (adjust to your location)
pihole_timezone: "America/Denver"

# Upstream DNS servers (semicolon-separated)
# Options:
# - Cloudflare: 1.1.1.1;1.0.0.1
# - Google: 8.8.8.8;8.8.4.4
# - Quad9: 9.9.9.9;149.112.112.112
# - OpenDNS: 208.67.222.222;208.67.220.220
pihole_dns_servers: "9.9.9.9;149.112.112.112"

# Enable DNSSEC validation
pihole_dnssec: "true"

# IPv6 support
pihole_ipv6: "true"

# ============================================
# Admin Interface
# ============================================
# IMPORTANT: Override pihole_admin_password in pihole_vault.yml
# Never commit plaintext passwords to git
pihole_admin_password: "{{ vault_pihole_admin_password | default('changeme123') }}"

pihole_web_theme: "default-dark"
pihole_temperature_unit: "f"

# ============================================
# Network Configuration
# ============================================
# Server IP for Pi-hole (optional - auto-detected if blank)
# Set this to the expected LoadBalancer IP if you want consistency
pihole_server_ip: ""

# Service type - LoadBalancer uses MetalLB
pihole_service_type: "MetalLB"

# LoadBalancer IP (optional - leave empty for auto-assignment)
# If you want a specific IP from MetalLB pool, set it here
# Example: "10.41.0.53" (traditional DNS port number)
pihole_loadbalancer_ip: ""

# Service annotations for MetalLB
pihole_service_annotations:
  metallb.universe.tf/address-pool: "default"
  # Allow DNS and Web to share the same IP (optional)
  metallb.universe.tf/allow-shared-ip: "pihole-svc"

# ============================================
# Storage Configuration
# ============================================
pihole_storage_enabled: true
pihole_storage_class: "longhorn"
pihole_storage_size: "5Gi"
pihole_storage_access_mode: "ReadWriteOnce"

# ============================================
# Resource Limits
# ============================================
# Adjust based on your cluster resources and usage patterns
pihole_resources_requests_cpu: "100m"
pihole_resources_requests_memory: "256Mi"
pihole_resources_limits_cpu: "500m"
pihole_resources_limits_memory: "512Mi"

# ============================================
# Advanced DNS Configuration
# ============================================
# Conditional forwarding (for local domain resolution)
pihole_conditional_forwarding: "true"
pihole_conditional_forwarding_domain: "lab.hashgrid.net"
pihole_conditional_forwarding_target: "10.2.0.1"
pihole_conditional_forwarding_router: "10.2.0.1"

# Reverse DNS server
pihole_rev_server: "true"
pihole_rev_server_domain: "lab.hashgrid.net"
pihole_rev_server_target: "10.2.0.1"
pihole_rev_server_cidr: "10.2.0.0/24"

# Query logging
pihole_query_logging: "true"

# ============================================
# Custom DNS Records
# ============================================
# Define custom DNS A records
pihole_custom_dns_records:
  - domain: "homelab.local"
    ip: "10.2.0.100"
  # - domain: "nas.homelab.local"
  #   ip: "192.168.1.50"
  # - domain: "media.homelab.local"
  #   ip: "192.168.1.51"

# Define custom CNAME records
pihole_custom_cname_records: []
  # - domain: "plex.homelab.local"
  #   target: "media.homelab.local"
  # - domain: "jellyfin.homelab.local"
  #   target: "media.homelab.local"

# ============================================
# Additional Environment Variables
# ============================================
pihole_extra_env_vars:
  # DNSMASQ_LISTENING: "all"
  # PIHOLE_DOMAIN: "homelab.local"
  # DHCP_ACTIVE: "false"
  # DHCP_START: "192.168.1.100"
  # DHCP_END: "192.168.1.200"
  # DHCP_ROUTER: "192.168.1.1"
  # DHCP_LEASETIME: "24"

# ============================================
# Health Checks
# ============================================
pihole_liveness_probe_enabled: true
pihole_liveness_probe_initial_delay: 60
pihole_liveness_probe_period: 10

pihole_readiness_probe_enabled: true
pihole_readiness_probe_initial_delay: 30
pihole_readiness_probe_period: 10

# ============================================
# Deployment Configuration
# ============================================
pihole_replicas: 1
pihole_update_strategy: "Recreate"
