---
# Ubuntu Baseline Configuration Playbook
# Applies basic security and utility configurations to all Ubuntu servers

- name: Apply baseline configuration to Ubuntu servers
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      tags: [packages]

    - name: Install baseline packages
      ansible.builtin.apt:
        name:
          - fail2ban
          - nmap
          - zsh
        state: present
      tags: [packages]

    - name: Ensure fail2ban is enabled and running
      ansible.builtin.systemd:
        name: fail2ban
        enabled: true
        state: started
      tags: [security]

    - name: Configure UFW - Allow SSH
      community.general.ufw:
        rule: allow
        name: OpenSSH
      tags: [firewall, security]

    - name: Configure UFW - Enable firewall
      community.general.ufw:
        state: enabled
        policy: deny
        direction: incoming
      tags: [firewall, security]

    - name: Display baseline configuration summary
      ansible.builtin.debug:
        msg: |
          ============================================
          Ubuntu Baseline Configuration Complete
          ============================================
          Packages Installed:
            - fail2ban (intrusion prevention)
            - nmap (network scanning)
            - zsh (advanced shell)

          Security:
            - fail2ban enabled and running
            - UFW firewall enabled
            - SSH access allowed
            - Default incoming policy: DENY
          ============================================
      tags: [always]
