---
# Longhorn Default Variables
# Override these in group_vars or inventory as needed

# ============================================
# Longhorn Version
# ============================================
longhorn_version: "v1.7.2"  # Latest stable version
longhorn_chart_version: "1.7.2"

# ============================================
# Longhorn Namespace
# ============================================
longhorn_namespace: "longhorn-system"

# ============================================
# Helm Repository
# ============================================
longhorn_helm_repo_name: "longhorn"
longhorn_helm_repo_url: "https://charts.longhorn.io"
longhorn_helm_chart_name: "longhorn"

# ============================================
# Storage Configuration
# ============================================
# Default storage path on each node
longhorn_default_data_path: "/var/lib/longhorn"

# Default storage class settings
longhorn_default_storage_class: true
longhorn_storage_class_name: "longhorn"
longhorn_storage_retain_policy: "Delete"  # Options: Delete, Retain

# Number of replicas for volumes
longhorn_default_replica_count: 3

# ============================================
# Node Selector & Tolerations
# ============================================
# Install on all worker nodes by default
longhorn_node_selector: {}
  # kubernetes.io/os: linux
  # storage: "true"

longhorn_tolerations: []
  # - key: "storage"
  #   operator: "Equal"
  #   value: "true"
  #   effect: "NoSchedule"

# ============================================
# Resource Requests & Limits
# ============================================
longhorn_manager_cpu_request: "100m"
longhorn_manager_memory_request: "128Mi"
longhorn_driver_cpu_request: "100m"
longhorn_driver_memory_request: "128Mi"
longhorn_ui_cpu_request: "100m"
longhorn_ui_memory_request: "128Mi"

# ============================================
# UI Configuration
# ============================================
longhorn_ui_enable: true
longhorn_ui_service_type: "ClusterIP"  # Options: ClusterIP, NodePort, LoadBalancer

# ============================================
# Ingress Configuration
# ============================================
longhorn_ingress_enabled: false
longhorn_ingress_host: "longhorn.example.com"
longhorn_ingress_tls_enabled: false
longhorn_ingress_annotations: {}
  # kubernetes.io/ingress.class: nginx
  # cert-manager.io/cluster-issuer: letsencrypt-prod

# ============================================
# Backup Configuration
# ============================================
# Backup target (S3, NFS, etc.)
longhorn_backup_target: ""  # Example: "s3://bucket@region/path"
longhorn_backup_target_secret: ""

# ============================================
# Advanced Options
# ============================================
longhorn_enable_upgrade_checker: true
longhorn_default_longhorn_static_storage_class: "longhorn-static"

# Guaranteed instance manager CPU
longhorn_guaranteed_instance_manager_cpu: "12"

# ============================================
# Prerequisites Check
# ============================================
# Required packages for Longhorn
longhorn_required_packages:
  - open-iscsi
  - nfs-common
  - util-linux
  - curl

# Required kernel modules
longhorn_required_modules:
  - iscsi_tcp
  - nbd

# ============================================
# Installation Mode
# ============================================
# Use Helm for installation (recommended)
longhorn_install_method: "helm"  # Options: helm, kubectl
